version: "3"

services:

    database:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: mytapp
        ports:
            - 5433:5432
